# Generated by Django 5.2.7 on 2025-11-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_designation_customuser_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Associate_Professor', 'Associate Professor'), ('Assistant_Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer'), ('PhD_Student', 'PhD student'), ('MSc_Student', 'MSc Student'), ('BSc_Student', 'BSc Student'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
