# Generated by Django 5.2.7 on 2025-11-20 10:02

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='session',
            field=models.CharField(blank=True, choices=users.models.get_session_choices, max_length=9, null=True),
        ),
    ]
