# Generated by Django 5.2.7 on 2025-11-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='session',
            field=models.CharField(blank=True, choices=[('2026-2027', '2026-2027'), ('2025-2026', '2025-2026'), ('2024-2025', '2024-2025'), ('2023-2024', '2023-2024'), ('2022-2023', '2022-2023'), ('2021-2022', '2021-2022'), ('2020-2021', '2020-2021'), ('2019-2020', '2019-2020'), ('2018-2019', '2018-2019'), ('2017-2018', '2017-2018'), ('2016-2017', '2016-2017'), ('2015-2016', '2015-2016'), ('2014-2015', '2014-2015'), ('2013-2014', '2013-2014'), ('2012-2013', '2012-2013'), ('2011-2012', '2011-2012'), ('2010-2011', '2010-2011')], max_length=9, null=True),
        ),
    ]
