# Generated by Django 5.2.7 on 2025-11-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='branch',
            field=models.CharField(blank=True, choices=[('dhaka', 'Dhaka'), ('chittagong', 'Chittagong')], max_length=15, null=True),
        ),
    ]
