# Generated by Django 5.2.7 on 2025-11-16 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0002_intern_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern_instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intern',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='intern_instructors', to=settings.AUTH_USER_MODEL),
        ),
    ]
