# Generated by Django 5.2.7 on 2025-11-17 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0003_intern_instructor_intern_instructors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='medium',
        ),
    ]
