# Generated by Django 5.2.7 on 2025-11-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0004_remove_intern_branch_remove_intern_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='syllabus',
            field=models.URLField(blank=True, help_text='Link to the syllabus document or page', null=True),
        ),
    ]
