# Generated by Django 5.2.7 on 2025-11-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0006_interncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
