# Generated by Django 5.2.7 on 2025-11-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_url', models.URLField(help_text='Embed YouTube video link (e.g., https://www.youtube.com/embed/abcdef)')),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
