# Generated by Django 5.2.7 on 2025-11-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_vlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlog',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vlog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
