# Generated by Django 5.2.7 on 2025-11-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_vlog_author_vlog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='author',
            field=models.CharField(blank=True, null=True),
        ),
    ]
