# Generated by Django 5.2.7 on 2025-11-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_vlog_description_alter_vlog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('journal', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
