# Generated by Django 5.2.7 on 2025-11-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_researchpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='research_papers/'),
        ),
    ]
