# Generated by Django 5.2.7 on 2025-12-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpost_category_vlog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
