# Generated by Django 5.2.7 on 2025-10-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonOrder',
        ),
    ]
