# Generated by Django 5.2.7 on 2025-10-13 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_delete_lessonorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='courses.lesson'),
        ),
    ]
