# Generated by Django 5.2.7 on 2025-10-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_exam_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='enrolled_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
