# Generated by Django 5.2.7 on 2025-10-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseprogress_enrolled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examprogress',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
