# Generated by Django 5.2.7 on 2025-10-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_examprogress_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
