# Generated by Django 5.2.7 on 2025-10-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_examattempt_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examprogress',
            options={},
        ),
        migrations.RemoveField(
            model_name='examprogress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='videoprogress',
            name='completed_at',
        ),
        migrations.AlterField(
            model_name='examprogress',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LessonProgress',
        ),
    ]
