# Generated by Django 5.2.7 on 2025-10-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_examprogress_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseprogress',
            old_name='updated_at',
            new_name='completed_at',
        ),
    ]
