# Generated by Django 5.2.7 on 2025-10-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='issued_at',
        ),
    ]
