# Generated by Django 5.2.7 on 2025-10-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_certificate_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
