# Generated by Django 5.2.7 on 2025-11-10 12:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_category_icon_category_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
