# Generated by Django 5.2.7 on 2025-11-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_course_instructor_course_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor',
            new_name='instructors',
        ),
    ]
