# Generated by Django 5.2.7 on 2025-11-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_instructor_alter_course_instructors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Course Comments'},
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
