# Generated by Django 5.2.7 on 2025-11-09 05:17

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('medium', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('video', models.URLField(help_text='YouTube video URL')),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='trainings/')),
            ],
            options={
                'ordering': ['order', '-date'],
            },
        ),
    ]
