# Generated by Django 5.2.7 on 2025-11-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_training_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='training',
            name='summary',
            field=models.TextField(default=1, help_text='Short summary to display in list view.', max_length=500),
            preserve_default=False,
        ),
    ]
