# Generated by Django 5.2.7 on 2025-11-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_training_slug_training_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='branch',
            field=models.CharField(blank=True, choices=[('dhaka', 'Dhaka'), ('chittagong', 'Chittagong')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='platform',
            field=models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('google_meet', 'Meet')], max_length=15, null=True),
        ),
    ]
