# Generated by Django 5.2.7 on 2025-11-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_training_current_price_training_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
    ]
