# Generated by Django 5.2.7 on 2025-11-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_training_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='platform',
            field=models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet')], max_length=15, null=True),
        ),
    ]
