# Generated by Django 5.2.7 on 2025-11-15 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_alter_training_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='instructors',
            field=models.ManyToManyField(blank=True, null=True, related_name='training_instructors', to=settings.AUTH_USER_MODEL),
        ),
    ]
