# Generated by Django 5.2.7 on 2025-11-16 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_trainingcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='training_instructors', to=settings.AUTH_USER_MODEL),
        ),
    ]
