# Generated by Django 5.2.7 on 2025-11-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_alter_training_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='professional_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
    ]
